#
# Changes from the original:
#
# - Root URL under Istio VirtualService:
#
#     [server]
#     protocol: http
#     domain: localhost
#     root_url: http://localhost:7080/grafana
#     serve_from_sub_path: true
#     router_logging: true
#     http_port: 3000
#
#   From:
#       https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#server
#
# - Unauthenticated ("anonymous") access:
#
#     [auth.anonymous]
#     enabled = true
#     org_name = Main Org.
#     org_role = Viewer
#
#   (Unfortunately so far Grafana still asks for user ID and password :( )
#
#   From:
#       https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/#anonymous-authentication
#
# - Also added:
#
#       [auth]
#       disable_login_form = true
#
#   From:
#       https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/grafana/
#
# - Allow embedding Grafana views inside Rook/Ceph dashboard, though we
#   have not yet finished configuring the Rook/Ceph side, according to
#   the Ceph documentation:
#
#       [security]
#       allow_embedding = true
#
#   From:
#       https://docs.ceph.com/en/latest/mgr/dashboard/#enabling-the-embedding-of-grafana-dashboards
#
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 10.3.1
  name: grafana-config
  namespace: monitoring
stringData:
  grafana.ini: |
    [date_formats]
    default_timezone = UTC
    [server]
    protocol: http
    domain: localhost
    root_url: http://localhost:7080/grafana
    serve_from_sub_path: false
    router_logging: true
    http_port: 3000
    [auth.anonymous]
    enabled = true
    org_name = Main Org.
    org_role = Viewer
    [auth]
    disable_login_form = true
    [security]
    allow_embedding = true
type: Opaque
