---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubedemo
    app.kubernetes.io/instance: dbadmin
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/part-of: kubedemo
  name: dbadmin
  namespace: db
