#
# Ory Oathkeeper access rules.
#
# Initially we only enable anonymous access to all VirtualServices.
#
# Later, once our identity management system (Ory Kratos) is spun up
# in the platform layer, we disable anonymous access, and turn on
# proper authentication.  See the platform layer for details.
#
# Full YAML allowed in access-rules.yaml:
#
#     https://www.ory.sh/docs/oathkeeper/reference/configuration
#
# Apache 2.0 license:
#
#     https://github.com/ory/k8s/blob/v0.39.1/LICENSE
#
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: ory-oathkeeper
    app.kubernetes.io/name: ory-oathkeeper
  name: access-rules
  namespace: auth
data:
  access-rules.yaml: |-
    #
    # allow-all-anonymous:
    # Anyone and everyone is allowed to do anything and everything.
    #
    - id: allow-all-anonymous
      version: v1.0.0
      match:
        url: http://.*

      authenticators:
        - handler: anonymous
          config:
            subject: anonymous
      
      authorizer:
        handler: allow

      #
      # Generate a JWT (id_token) so that Istio can use Ory Oathkeeper
      # to authenticate (even for our anonymous user).
      #
      #     https://istio.io/latest/docs/tasks/security/authentication/authn-policy/#end-user-authentication
      #     https://www.ory.sh/docs/oathkeeper/pipeline/mutator#id_token
      #
      mutators:
        - handler: id_token
