---
#
# Tell Prometheus about Services in the rook-ceph namespace, for observability.
#
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: rook-ceph-mgr
    rook_cluster: rook-ceph
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/name: rook-ceph
  name: rook-ceph
  namespace: rook-ceph
spec:
  endpoints:
  - interval: 30s
    params:
      format:
      - prometheus
    path: /metrics
    # Port 9283 "http-metrics":
    port: http-metrics
    scheme: http
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - rook-ceph
  selector:
    matchLabels:
      app: rook-ceph-mgr
