#
# From:
#
#     https://rook.io/docs/rook/v1.13/Storage-Configuration/Object-Storage-RGW/object-storage/#create-a-local-object-store
#
# Also:
#
#     https://rook.io/docs/rook/v1.13/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-claim/#example
#
# Modified from the original:
#
# - ObjectBucketClaim.metadata.name changed to "loki-chunks", etc.
# - ObjectBucketClaim.spec.generateBucketName changed to "loki-chunks", etc.
# - ObjectBucketClaim.spec.storageClassName changed to "kubedemo-s3-bucket"
#   to reference the StorageClass in storage-rook-s3.yaml
# - ObjectBucketClaim.spec.additionalConfig added,
#   with maxSize set to 1G for chunks, 256M for ruler and admin
#
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: loki-bucket
  namespace: logs
spec:
  generateBucketName: loki-bucket
  storageClassName: kubedemo-s3-bucket
  additionalConfig:
    maxSize: "1G"
# !!! ---
# !!! apiVersion: objectbucket.io/v1alpha1
# !!! kind: ObjectBucketClaim
# !!! metadata:
# !!!   name: loki-chunks
# !!!   namespace: logs
# !!! spec:
# !!!   generateBucketName: loki-chunks
# !!!   storageClassName: kubedemo-s3-bucket
# !!!   additionalConfig:
# !!!     maxSize: "1G"
# !!! ---
# !!! apiVersion: objectbucket.io/v1alpha1
# !!! kind: ObjectBucketClaim
# !!! metadata:
# !!!   name: loki-ruler
# !!!   namespace: logs
# !!! spec:
# !!!   generateBucketName: loki-ruler
# !!!   storageClassName: kubedemo-s3-bucket
# !!!   additionalConfig:
# !!!     maxSize: "256M"
# !!! ---
# !!! apiVersion: objectbucket.io/v1alpha1
# !!! kind: ObjectBucketClaim
# !!! metadata:
# !!!   name: loki-admin
# !!!   namespace: logs
# !!! spec:
# !!!   generateBucketName: loki-admin
# !!!   storageClassName: kubedemo-s3-bucket
# !!!   additionalConfig:
# !!!     maxSize: "256M"
