#
# Request a certificate from cert-manager, signed by our kubedemo root CA,
# for Vault's TLS handshaking.
#
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: vault
spec:
  secretName: vault-tls
  duration: 2160h  # 90 days - fine for our kubedemo.
  renewBefore: 360h  # 15 days - fine for our kubedemo.
  subject:
    organizations:
      - vault
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  # commonName: example.com
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, IP address or otherName is required.
  dnsNames:
    - vault.kubedemo
  uris:
    - spiffe://cluster.local/ns/vault/sa/vault
  issuerRef:
    name: kubedemo-issuer
    kind: ClusterIssuer
